// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqcppzrwatagnnwspowm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxY3BwenJ3YXRhZ25ud3Nwb3dtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjUwNDAsImV4cCI6MjA2NzkwMTA0MH0.5kuUsyp3AvDx5C21SBA11kMlNLlPZrEhHoEW9wwleKw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});